// Generated by CoffeeScript 1.10.0
(function() {
  var app, express, fs, http, io, mime, multipart, multipartMiddleware, server, util,bodyParser,path, moniker;

  moniker = require('Moniker')

  path = require('path');

  express = require('express');

  http = require('http');

  app = express();

  server = http.createServer(app);

  io = require('socket.io')(server);

  util = require("util");

  mime = require("mime");

  fs = require("fs");

  multipart = require('connect-multiparty');

  bodyParser = require('body-parser');

  multipartMiddleware = multipart();

  
  app.use(express["static"]('public'));

  app.post('/images', multipartMiddleware, function(req, res) {
    console.log(req);
    
    var tmpPath,targetPath;
    var date = new Date();
    var d = (date.getMonth() + 1) + "-" + date.getDate() + "-" + date.getHours() + "-" + date.getMinutes() + "-" + date.getSeconds();

    tmpPath = req.files.file.path;
    targetPath = path.resolve('./public/images/'+ d + '.gif');

// public以下に移動
	fs.rename(tmpPath, targetPath, function(err) {
		if (err) throw err;
		// 一時ファイルを削除

		fs.unlink(tmpPath, function() {
		    if (err) throw err;
		    res.send('File uploaded to: ' + targetPath + ' - ' + req.files.file.size + ' bytes');
		});
	});    
    return fs.readFile(targetPath, function(err, buf) {
      var data;
      if (err != null) {
        res.status(422);
        return;
      }
      data = buf.toString('base64');
      io.sockets.emit('push image', {
        dataUrl: util.format("data:%s;base64,%s", mime.lookup(targetPath), data)
      });
      console.log(targetPath);

      return res.end();
    });
  });



  server.listen(8000);

}).call(this);
